### ISSUE TITLE
Wait for database connection on boot

### ISSUE THREAD

**Issue by LucaScorpion** [Tocabi/clearcloud#81]
Currently when starting clearcloud, it will crash and exit if no database connection can be established. This is an issue when starting clearcloud and the db are started simultaneously, or in my case, when auto-updating my docker containers. Ideally I think it should just wait for a connection to be established.

**Comment by ChappIO** [comment]
The crash and restart is intentional because restarting inside a docker container refreshes the dns. So if your clearcloud container boots before the database container then the database dns name is not known yet. A reboot is required after the database container has started. As the README states: It's recommended to set the restart behavior to "unless-stopped".

However, this is a behaviour I haven't tested in 3 years or so, so I will retest and share my findings here.

**Comment by ChappIO** [comment]
Nope, that issue seems to be fixed! Awesome. I prepared a PR.

**Comment by LucaScorpion** [comment]
> It's recommended to set the restart behavior to "unless-stopped"

Fair, I must have glossed over that bit. Doesn't help that in unraid that's not a GUI option, but something you'd have to manually put in the "extra parameters" input box though :roll_eyes: 

Either way, nice that that's improved now, and ofc good to have this built in imo :) Will have a look at the pr!
